/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cdecimo;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.WindowListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import cdecimo.listaIU;
/**
 *
 * @author juliu
 */


public class InterfazGestion extends javax.swing.JFrame {

    private Font f;
    BDHelper bd;
    /**
     * Creates new form InterfazGestion
     */
    ConjuntoDecimos decimos = ConjuntoDecimos.getInstance();
    int numero;
    public InterfazGestion() throws IOException {
        bd = new BDHelper();
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaIU1.setBDHelper(this.bd);
        this.listaIU1.setVisible(false);
        this.old.setVisible(false);
        this.ventaUI1.setVisible(false);
        this.addUI1.setVisible(false);
        try {
            
            this.topPanel.setBackground(new Color(12,89,207, 76));
            this.jPanel1.setBackground(new Color(12,89,207, 0));
            this.container.setBackground(new Color(12,89,207, 0));
            Font f=Font.createFont(Font.TRUETYPE_FONT, getClass().getResource("Roboto-Regular.ttf").openStream());
            GraphicsEnvironment genv = GraphicsEnvironment.getLocalGraphicsEnvironment();
            genv.registerFont(f);
            f= f.deriveFont(26f);
            this.titulo.setFont(f);
            f= f.deriveFont(18f);
            this.subheader.setFont(f);
            //this.jLabel3.setFont(f);
            
            f = f.deriveFont(15f);
            this.jTextFieldCodBarras.setFont(f);
            this.jTextFieldConsultaNum.setFont(f);
            this.n_registrados_label.setFont(f);
            this.nTotal.setFont(f);
            this.nVendidosLabel.setFont(f);
            this.jTextAreaCantidad.setFont(f);
            this.jTextAreaCantidad.setAlignmentX(CENTER_ALIGNMENT);

            this.disponibleLabel.setFont(f);
            this.vendidosLabel.setFont(f);
            this.vendidosText.setFont(f);
            this.vendidosText.setAlignmentX(CENTER_ALIGNMENT);
            
            this.nTotal.setText(String.valueOf(bd.getCantidadTotal()));
            this.nVendidos.setText(String.valueOf(bd.totalVendidos()));
            System.out.println("Tenemos "+bd.getCantidadTotal()+" numeros registrados");
            
            
        } catch (FontFormatException ex) {
            Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lateral = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        menu = new javax.swing.JPanel();
        btnpanelLista = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnpanelAdd = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnpanelDelete = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        addUI1 = new cdecimo.AddUI();
        listaIU1 = new cdecimo.listaIU();
        background = new javax.swing.JLabel();
        ventaUI1 = new cdecimo.VentaUI();
        old = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        izq = new javax.swing.JPanel();
        jLabelCodBarras = new javax.swing.JLabel();
        jButtonConsultaCodigo = new javax.swing.JButton();
        jTextFieldConsultaNum = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        disponibleLabel = new javax.swing.JLabel();
        vendidosLabel = new javax.swing.JLabel();
        jTextAreaCantidad = new javax.swing.JLabel();
        vendidosText = new javax.swing.JLabel();
        dcha = new javax.swing.JPanel();
        jButtonAniadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldCodBarras = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        nVendidosLabel = new javax.swing.JLabel();
        n_registrados_label = new javax.swing.JLabel();
        nTotal = new javax.swing.JLabel();
        nVendidos = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        subheader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lotería Los Dos Patitos");
        setMaximumSize(new java.awt.Dimension(1265, 574));
        setMinimumSize(new java.awt.Dimension(1265, 574));
        setPreferredSize(new java.awt.Dimension(1265, 574));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lateral.setBackground(new java.awt.Color(0, 75, 160));
        lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Los Dos Patos");
        lateral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lotería");
        lateral.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 80));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        lateral.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 10));

        menu.setBackground(new java.awt.Color(0, 75, 160));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnpanelLista.setBackground(new java.awt.Color(0, 75, 160));
        btnpanelLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpanelListaMousePressed(evt);
            }
        });
        btnpanelLista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_format_list_bulleted_white_36dp.png"))); // NOI18N
        btnpanelLista.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lista");
        btnpanelLista.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 40));

        menu.add(btnpanelLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 60));

        btnpanelAdd.setBackground(new java.awt.Color(0, 75, 160));
        btnpanelAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpanelAddMousePressed(evt);
            }
        });
        btnpanelAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_library_add_white_36dp.png"))); // NOI18N
        btnpanelAdd.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Añadir");
        btnpanelAdd.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 40));

        menu.add(btnpanelAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 60));

        btnpanelDelete.setBackground(new java.awt.Color(0, 75, 160));
        btnpanelDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpanelDeleteMousePressed(evt);
            }
        });
        btnpanelDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_add_shopping_cart_white_36dp.png"))); // NOI18N
        jLabel10.setToolTipText("");
        btnpanelDelete.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vender");
        btnpanelDelete.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 40));

        menu.add(btnpanelDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 60));

        lateral.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, 390));

        getContentPane().add(lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 272, 574));

        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        container.add(addUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));
        container.add(listaIU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bombo.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(836, 493));
        background.setMinimumSize(new java.awt.Dimension(836, 493));
        background.setPreferredSize(new java.awt.Dimension(836, 493));
        container.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 1130, 580));
        container.add(ventaUI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));

        old.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 219, 11));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izq.setBackground(new java.awt.Color(12, 89, 207));
        izq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izqMouseClicked(evt);
            }
        });
        izq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCodBarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-25.png"))); // NOI18N
        izq.add(jLabelCodBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 24, 24));

        jButtonConsultaCodigo.setText("Consulta cantidad");
        jButtonConsultaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultaCodigoActionPerformed(evt);
            }
        });
        izq.add(jButtonConsultaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 180, 30));

        jTextFieldConsultaNum.setBackground(new java.awt.Color(12, 89, 207));
        jTextFieldConsultaNum.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldConsultaNum.setBorder(null);
        jTextFieldConsultaNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldConsultaNumMouseClicked(evt);
            }
        });
        jTextFieldConsultaNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldConsultaNumActionPerformed(evt);
            }
        });
        jTextFieldConsultaNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldConsultaNumKeyPressed(evt);
            }
        });
        izq.add(jTextFieldConsultaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 221, 40));
        izq.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 258, -1));

        disponibleLabel.setForeground(new java.awt.Color(255, 255, 255));
        disponibleLabel.setText("Disponible");
        izq.add(disponibleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 145, 20));

        vendidosLabel.setForeground(new java.awt.Color(255, 255, 255));
        vendidosLabel.setText("Vendidos");
        izq.add(vendidosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 145, 20));

        jTextAreaCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaCantidad.setText("---");
        izq.add(jTextAreaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        vendidosText.setForeground(new java.awt.Color(255, 255, 255));
        vendidosText.setText("---");
        izq.add(vendidosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jPanel1.add(izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 308, 205));

        dcha.setBackground(new java.awt.Color(12, 89, 207));
        dcha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dchaMouseClicked(evt);
            }
        });
        dcha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAniadir.setText("Añadir");
        jButtonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAniadirActionPerformed(evt);
            }
        });
        dcha.add(jButtonAniadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jButtonBorrar.setText("Vender");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        dcha.add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, -1));

        jLabel2.setText("Cantidad actual");
        dcha.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jLabelCantidad.setText("Cantidad");
        dcha.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jTextFieldCodBarras.setBackground(new java.awt.Color(12, 89, 207));
        jTextFieldCodBarras.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldCodBarras.setText("00000000000000000000");
        jTextFieldCodBarras.setBorder(null);
        jTextFieldCodBarras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCodBarrasMouseClicked(evt);
            }
        });
        dcha.add(jTextFieldCodBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 190, 40));
        dcha.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 222, 2));
        dcha.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 62, 22));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barcode_icon.png"))); // NOI18N
        dcha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        nVendidosLabel.setForeground(new java.awt.Color(255, 255, 255));
        nVendidosLabel.setText("Números vendidos: ");
        dcha.add(nVendidosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        n_registrados_label.setForeground(new java.awt.Color(255, 255, 255));
        n_registrados_label.setText("Números registrados: ");
        dcha.add(n_registrados_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        nTotal.setForeground(new java.awt.Color(255, 255, 255));
        nTotal.setText("000");
        dcha.add(nTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        nVendidos.setForeground(new java.awt.Color(255, 255, 255));
        nVendidos.setText("000");
        dcha.add(nVendidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jPanel1.add(dcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 60, 308, 205));

        old.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1110, 430));

        topPanel.setBackground(new java.awt.Color(12, 89, 207));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(12, 89, 207));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Lotería Los Dos Patitos");
        topPanel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 42, 271, 36));

        subheader.setForeground(new java.awt.Color(255, 255, 255));
        subheader.setText("Gestión de décimos");
        subheader.setPreferredSize(new java.awt.Dimension(159, 15));
        topPanel.add(subheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 85, 159, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dospatos.png"))); // NOI18N
        topPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, 125, 129));

        old.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 156));

        container.add(old, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
   
    Este boton comprueba si el codigo de barras introducido pertenece al conjunto de decimos
    si es asi solo se le aniade la cantidad marcada en la casilla de cantidad, sino
    se activa el boton de insertar.
   
*/
    private void jButtonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAniadirActionPerformed
        // TODO add your handling code here:
        
        Decimo dec = null;
       // long cod = Long.parseLong(jTextFieldCodBarras.getText());
        String cod = jTextFieldCodBarras.getText();
        String numeroDecimo = cod.substring(11, 16);
        if(!cod.isEmpty()){
            dec = bd.consultar(numeroDecimo);
        }
        int cantidad = (int) this.jSpinner1.getValue();
        
        //int cantidad = this.jTextFieldIntCant.getText()!=""?Integer.parseInt(this.jTextFieldIntCant.getText().trim()):0;         
        if (dec==null){
            dec = new Decimo(numeroDecimo, cod, cantidad, 0);
            bd.insertar(dec);
        }else{
            System.out.println(dec.toBD());
            JOptionPane.showMessageDialog(this, "El decimo ya esta en la base de datos. Se ha aumentado la cantidad");
            dec.aumentarCantidad(cantidad);
        }           
        //jTextFieldIntCant.setText("");
        nTotal.setText(String.valueOf(bd.getCantidadTotal()));
                    System.out.println("Tenemos "+bd.getCantidadTotal()+" numeros registrados");
        this.nVendidos.setText(String.valueOf(bd.totalVendidos()));
    
    }//GEN-LAST:event_jButtonAniadirActionPerformed
/*
    
    Boton para coger el codigo de barras del cuadro de consulta y ver si se encuentra en el decimo
    si lo hace muestra la cantidad en el recuadro de la cantidad
    
*/
    private void jButtonConsultaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultaCodigoActionPerformed
        // TODO add your handling code here:

        String cod = new String(this.jTextFieldConsultaNum.getText());
        String cnt = "";
        String vend = "";
        try {
            if( cod != "")
                cnt = String.valueOf(bd.getCantidadDisponible(cod));
                vend = String.valueOf(bd.getCantidadVendidos(cod));
        } catch (IOException ex) {
            Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTextAreaCantidad.setText(cnt);
        vendidosText.setText(vend);
        
    }//GEN-LAST:event_jButtonConsultaCodigoActionPerformed

    private void jTextFieldConsultaNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldConsultaNumKeyPressed
        // TODO add your handling code here:      
    }//GEN-LAST:event_jTextFieldConsultaNumKeyPressed

/*
    
    Borra la cantidad de decimo indicada a partir del numero del decimo.
    
    
    */
    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        Decimo dec = new Decimo();
        
       // long cod = Long.parseLong(jTextFieldCodBarras.getText());
        String cod = jTextFieldCodBarras.getText();
        int cantidad = (int) this.jSpinner1.getValue();//this.jTextFieldIntCant.getText()!=""?Integer.parseInt(this.jTextFieldIntCant.getText().trim()):0; 
        
            this.bd.borrar(cod,cantidad);

        /*
        
        if (!decimos.decimo_esta(cod)){
            //JOptionPane.showMessageDialog(this, "El decimo no esta. Introduce el numero y la cantidad a borrar");
            String numeroDecimo = "0";
            if(cod.length()>10)
                numeroDecimo = cod.substring(11, 16); 
            else if(cod.length()==5)
                numeroDecimo = cod;
            if(numeroDecimo!="0"){
                dec.setCodigoBarras(cod);
                dec.setNumeroDecimo(numeroDecimo);
                dec.aumentarCantidad(cantidad);
            }
        }else{
            //JOptionPane.showMessageDialog(this, "El decimo ya esta en la base de datos se ha aumentado la cantidad");
            try {
                   dec = bd.consultar(cod);
                   if (cantidad==0){
                       dec.borrarCantidad(1);
                       this.nTotal.setText(String.valueOf(bd.getCantidadTotal()));
                    }else if(cantidad>0){
                        dec.borrarCantidad(cantidad);
                        this.nTotal.setText(String.valueOf(bd.getCantidadTotal()));
                    }
                   else{
                    JOptionPane.showMessageDialog(this, "No puede introducir una cantidad negativa");
                   }
            } catch (IOException ex) {
                Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            //jTextFieldIntCant.setText("");
            this.jSpinner1.setValue(0);
            this.nTotal.setText(String.valueOf(bd.getCantidadTotal()));
            this.nVendidos.setText(String.valueOf(bd.totalVendidos()));
        
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldConsultaNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldConsultaNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldConsultaNumActionPerformed

    private void jTextFieldConsultaNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldConsultaNumMouseClicked
        // TODO add your handling code here:
        jTextFieldConsultaNum.setText("");
        jTextAreaCantidad.setText("");
    }//GEN-LAST:event_jTextFieldConsultaNumMouseClicked

    private void jTextFieldCodBarrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCodBarrasMouseClicked
        // TODO add your handling code here:
        this.jTextFieldCodBarras.setText("");
    }//GEN-LAST:event_jTextFieldCodBarrasMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            this.bd.save();
            System.exit(0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se ha podido guardar el fichero");
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void izqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izqMouseClicked
        // TODO add your handling code here:
        setColor(izq);
        resetColor(dcha);
    }//GEN-LAST:event_izqMouseClicked

    private void dchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dchaMouseClicked
        // TODO add your handling code here:
        setColor(dcha);
        resetColor(izq);
    }//GEN-LAST:event_dchaMouseClicked

    private void btnpanelListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpanelListaMousePressed
        try {
            // TODO add your handling code here:
            this.listaIU1.setBDHelper(this.bd);
            
        } catch (IOException ex) {
            Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setColor(btnpanelLista);
        resetColor(btnpanelAdd);
        resetColor(btnpanelDelete);
        
        this.listaIU1.setVisible(true);
        this.old.setVisible(false);
        this.ventaUI1.setVisible(false);
        this.background.setVisible(false);
                this.addUI1.setVisible(false);

    }//GEN-LAST:event_btnpanelListaMousePressed

    private void btnpanelAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpanelAddMousePressed
        // TODO add your handling code here:
        setColor(btnpanelAdd);
        resetColor(btnpanelLista);
        resetColor(btnpanelDelete);
        
        try {
            // TODO add your handling code here:
            this.addUI1.setBDHelper(this.bd);
            
        } catch (IOException ex) {
            Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.listaIU1.setVisible(false);
        this.addUI1.setVisible(true);
        this.ventaUI1.setVisible(false);
        this.background.setVisible(false);
    }//GEN-LAST:event_btnpanelAddMousePressed

    private void btnpanelDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpanelDeleteMousePressed
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            this.ventaUI1.setBDHelper(this.bd);
            
        } catch (IOException ex) {
            Logger.getLogger(InterfazGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setColor(btnpanelDelete);
        resetColor(btnpanelLista);
        resetColor(btnpanelAdd);
        
        this.listaIU1.setVisible(false);
        this.ventaUI1.setVisible(true);
        this.old.setVisible(false);
        this.background.setVisible(false);
        this.addUI1.setVisible(false);
    }//GEN-LAST:event_btnpanelDeleteMousePressed
    
    private void setColor(JPanel panel){
        panel.setBackground(new Color(99, 164, 255));
    }
    
    private void resetColor(JPanel panel){
         panel.setBackground(new Color(0, 75, 160));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        InterfazGestion interfaz = new InterfazGestion();
        interfaz.setIconImage(Toolkit.getDefaultToolkit()
                            .getImage(ConjuntoDecimos.class.getResource("/images/dospatos.png")));
                    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                interfaz.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cdecimo.AddUI addUI1;
    private javax.swing.JLabel background;
    private javax.swing.JPanel btnpanelAdd;
    private javax.swing.JPanel btnpanelDelete;
    private javax.swing.JPanel btnpanelLista;
    private javax.swing.JPanel container;
    private javax.swing.JPanel dcha;
    private javax.swing.JLabel disponibleLabel;
    private javax.swing.JPanel izq;
    private javax.swing.JButton jButtonAniadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonConsultaCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCodBarras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jTextAreaCantidad;
    private javax.swing.JTextField jTextFieldCodBarras;
    private javax.swing.JTextField jTextFieldConsultaNum;
    private javax.swing.JPanel lateral;
    private cdecimo.listaIU listaIU1;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel nTotal;
    private javax.swing.JLabel nVendidos;
    private javax.swing.JLabel nVendidosLabel;
    private javax.swing.JLabel n_registrados_label;
    private javax.swing.JPanel old;
    private javax.swing.JLabel subheader;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel vendidosLabel;
    private javax.swing.JLabel vendidosText;
    private cdecimo.VentaUI ventaUI1;
    // End of variables declaration//GEN-END:variables
}
